# Generated by Django 4.0.1 on 2022-01-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('aadhar_number', models.IntegerField()),
                ('roll_number', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('exam_center', models.CharField(max_length=50)),
 
            ],
        ),
    ]
